---
###############################################################################
#   JENKINS INSTALLATION & CONFIGURATION
###############################################################################

# install packages
- name: add jenkins key
  apt_key: url=http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key state=present
  tags: repository

- name: add jenkins repository
  apt_repository: repo='deb http://pkg.jenkins-ci.org/debian binary/' state=present
  tags: repository

- name: install jenkins and default apps
  apt: pkg={{item}} update_cache=yes state=installed
  with_items:
    - python-apt
    - python-pycurl
    - jenkins
  tags:
    - packages
  notify: restart jenkins

# setup user
- name: ensure jenkins is stopped
  service: name=jenkins state=stopped

- name: create jenkins user
  user: shell=/bin/bash name={{ user }} password={{ password }} home={{ homedir }} group={{ group }}
  notify: restart jenkins

# setup ssh_keys
- name: remove .ssh folder
  command: rm -rf ~/.ssh
  sudo_user: ${user}
  tags: ssh_keys

- name: create .ssh folder
  command: mkdir -p ~/.ssh creates=true
  sudo_user: ${user}
  tags: ssh_keys

- name: add ssh private key
  copy: src={{ ssh_keys_dir }}/{{ user }}/id_rsa dest=~/.ssh/id_rsa mode=700
  sudo_user: ${user}
  tags: ssh_keys

- name: add ssh public key
  copy: src={{ ssh_keys_dir }}/{{ user }}/id_rsa.pub dest=~/.ssh/id_rsa.pub
  sudo_user: ${user}
  tags: ssh_keys

# jenkins configuration
- name: configure jenkins
  template: src=jenkins.j2 dest=/etc/default/jenkins owner=root group=root mode=755
  tags: jenkins
  notify: restart jenkins

- name: configure nginx
  template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/jenkins owner=root group=root mode=755
  tags: nginx
  notify: restart nginx

- name: Configure nginx (link files)
  file: src=/etc/nginx/sites-available/jenkins dest=/etc/nginx/sites-enabled/jenkins state=link
  tags: nginx
  notify: restart nginx
