---
- name: default apps
  apt: pkg={{item}} state=installed
  with_items:
    - python-apt
    - python-pycurl
  tags:
    - packages

- name: add jenkins key
  apt_key: url=http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key state=present
  tags: repository

- name: add jenkins repository
  apt_repository: repo='deb http://pkg.jenkins-ci.org/debian binary/' state=present
  tags: repository

- name: install jenkins
  apt: pkg=jenkins update_cache=yes state=installed
  tags: packages
  notify: restart jenkins

- name: configure jenkins
  template: src=jenkins.j2 dest=/etc/default/jenkins owner=root group=root mode=755
  tags: jenkins
  notify: restart jenkins

- name: configure nginx
  template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/jenkins owner=root group=root mode=755
  tags: nginx
  notify: restart nginx

- name: Configure nginx (link files)
  file: src=/etc/nginx/sites-available/jenkins dest=/etc/nginx/sites-enabled/jenkins state=link
  tags: nginx
  notify: restart nginx
