---
###############################################################################
#   JENKINS INSTALLATION & CONFIGURATION
###############################################################################

- include: backup.yml

# install packages
- name: add jenkins key
  apt_key: url=http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key state=present
  tags: repository

- name: add jenkins repository
  apt_repository: repo='deb http://pkg.jenkins-ci.org/debian binary/' state=present
  tags: repository

- name: install jenkins and default apps
  apt: pkg={{item}} update_cache=yes state=installed
  with_items:
    - python-apt
    - python-pycurl
    - jenkins
  tags:
    - packages
  notify: restart jenkins

# setup user, ssh_keys
- service: name=jenkins state=stopped
- name: create jenkins user
  user: shell=/bin/bash name={{ user }} password={{ password }} home={{ homedir }} group={{ group }}
  notify: restart jenkins

- name: remove .ssh folder
  command: rm -rf ~/.ssh
  sudo_user: ${user}
  tags: ssh_keys

- name: create .ssh folder
  command: mkdir -p ~/.ssh creates=true
  sudo_user: ${user}
  tags: ssh_keys

- name: add ssh private key
  copy: src={{ ssh_keys_dir }}/{{ user }}/id_rsa dest=~/.ssh/id_rsa mode=700
  sudo_user: ${user}
  tags: ssh_keys

- name: add ssh public key
  copy: src={{ ssh_keys_dir }}/{{ user }}/id_rsa.pub dest=~/.ssh/id_rsa.pub
  sudo_user: ${user}
  tags: ssh_keys

# jenkins configuration
- name: configure jenkins
  template: src=jenkins.j2 dest=/etc/default/jenkins owner=root group=root mode=755
  tags: jenkins
  notify: restart jenkins

- name: configure nginx
  template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/jenkins owner=root group=root mode=755
  tags: nginx
  notify: restart nginx

- name: Configure nginx (link files)
  file: src=/etc/nginx/sites-available/jenkins dest=/etc/nginx/sites-enabled/jenkins state=link
  tags: nginx
  notify: restart nginx

# backup
- name: checkout backup repo
  git: repo=ssh://git@127.0.0.1/home/git/backup.git dest=/home/jenkins/backup.git version=master accept_hostkey=true update=false
  sudo_user: jenkins
  ignore_errors: yes
  tags:
    - backup
    - restore

- name: update backup repo (if possible)
  git: repo=ssh://git@127.0.0.1/home/git/backup.git dest=/home/jenkins/backup.git version=master accept_hostkey=true
  sudo_user: jenkins
  ignore_errors: yes
  tags:
    - backup
    - restore

- name: create backup folder (if necessary)
  command: mkdir -p {{ homedir }}/backup.git/{{ user }} creates=true
  tags: backup

- name: rsync jenkins to backup repo
  command: rsync -a --delete {{ install_dir }} {{ homedir }}/backup.git/{{ user }}
  sudo_user: jenkins
  tags: backup

- name: git stage backup
  command: git add {{ homedir }}/backup.git chdir={{ homedir }}/backup.git
  sudo_user: jenkins
  tags: backup

- name: git commit backup
  command: git commit -m "jenkins backup triggered by ansible" chdir={{ homedir }}/backup.git
  sudo_user: jenkins
  tags: backup

- name: git push backup
  command: git push origin master chdir={{ homedir }}/backup.git
  sudo_user: jenkins
  tags: backup

# restore
- name: rsync backup repo to jenkins
  command: rsync -a --delete {{ homedir }}/backup.git/{{ user }} {{ install_dir }}
  sudo_user: jenkins
  tags: restore
